apiVersion: v1
kind: Pod
metadata:
  name: giropops
spec:
  containers:
  - name: girus
    image: ubuntu
    args:
    - sleep
    - infinity
    volumeMounts:
    - name: first-emptydir
      mountPath: /giropops
  volumes:
  - name: first-emptydir
    emptyDir:
      sizeLimit: 256Mi