apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-sm-secret
            key: aws-access-key
            namespace: default
          secretAccessKeySecretRef:
            name: aws-sm-secret
            key: aws-secret-access-key
            namespace: default