apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    storage: local-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/storage/nginx/pv"
  storageClassName: standard