apiVersion: v1
kind: Service
metadata:
  name: licaodecasa-service
spec:
#  type: NodePort
  selector:
    app: meu-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30000